"""Generate one refined PNAD income dataset per available survey year.

All survey-year-specific extraction rules are read from
``data/metadata/df_metadata.xlsx``, generated by
``stage_00_build_metadata.py``. In addition to the annual missing-income code,
the project-wide sentinel values 999999, 9999999, and 99999999 are always
excluded before any per-capita transformation.
"""

from pathlib import Path
from time import perf_counter

import pandas as pd
from tqdm.auto import tqdm


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_METADATA_PATH = REPO_ROOT / "data" / "metadata" / "df_metadata.xlsx"
DEFAULT_RAW_PATH = REPO_ROOT / "data" / "raw"
DEFAULT_REFINED_PATH = REPO_ROOT / "data" / "refined"

GLOBAL_INCOME_SENTINELS = frozenset({999_999, 9_999_999, 99_999_999})

REQUIRED_METADATA_COLUMNS = {
    "ano",
    "pos_renda",
    "tam_renda",
    "pos_morador",
    "tam_morador",
    "missing_renda",
    "raw_subdir",
    "raw_pattern",
    "n_files",
}


def load_metadata(metadata_path=DEFAULT_METADATA_PATH):
    """Load and validate the metadata required to generate annual datasets."""
    metadata_path = Path(metadata_path)

    if not metadata_path.is_file():
        raise FileNotFoundError(
            f"Metadata not found: {metadata_path}. Run src/stage_00_build_metadata.py first."
        )

    df_metadata = pd.read_excel(
        metadata_path,
        dtype={"raw_subdir": "string"},
    )

    missing_columns = REQUIRED_METADATA_COLUMNS.difference(df_metadata.columns)
    if missing_columns:
        raise ValueError(
            "Incomplete metadata. Missing columns: "
            + ", ".join(sorted(missing_columns))
        )

    if not df_metadata["ano"].is_unique:
        raise ValueError("Metadata contains duplicated years.")

    return df_metadata


def get_available_specs(df_metadata):
    """Return survey years with a complete ingestion specification."""
    available = df_metadata.loc[
        df_metadata["pos_renda"].notna()
        & df_metadata["tam_renda"].notna()
        & df_metadata["raw_pattern"].notna()
        & (df_metadata["raw_pattern"].astype(str).str.strip() != "")
        & (df_metadata["n_files"].fillna(0) > 0)
        & df_metadata["missing_renda"].notna()
    ].copy()

    return available.sort_values("ano").reset_index(drop=True)


def get_source_files(spec, raw_path=DEFAULT_RAW_PATH):
    """Resolve and validate the raw files declared for one survey year."""
    raw_path = Path(raw_path)
    folder = raw_path

    if pd.notna(spec.raw_subdir):
        raw_subdir = str(spec.raw_subdir).strip()
        if raw_subdir:
            folder = folder / raw_subdir

    if not folder.is_dir():
        raise FileNotFoundError(
            f"Raw-data directory not found for {int(spec.ano)}: {folder}"
        )

    pattern = str(spec.raw_pattern).strip()
    files = sorted(path for path in folder.glob(pattern) if path.is_file())

    expected = int(spec.n_files)
    if len(files) != expected:
        raise RuntimeError(
            f"Expected {expected} file(s) for {int(spec.ano)}, "
            f"found {len(files)} in {folder} with pattern '{pattern}': "
            + ", ".join(path.name for path in files)
        )

    return files


def _parse_int_field(line, start, end):
    field = line[start:end].strip()
    if not field:
        return None

    try:
        return int(field)
    except ValueError:
        return None


def read_year_fast(spec, raw_path=DEFAULT_RAW_PATH, show_file_progress=True):
    """Read, filter, and transform one survey year."""
    year = int(spec.ano)
    files = get_source_files(spec, raw_path=raw_path)

    income_start = int(spec.pos_renda)
    income_end = income_start + int(spec.tam_renda)
    missing_income = int(spec.missing_renda)

    has_member = pd.notna(spec.pos_morador) and pd.notna(spec.tam_morador)
    if has_member:
        member_start = int(spec.pos_morador)
        member_end = member_start + int(spec.tam_morador)

    incomes = []
    n_raw = 0
    n_missing_income = 0
    n_invalid_income = 0
    n_invalid_member = 0

    for file in files:
        file_size = file.stat().st_size
        progress = tqdm(
            total=file_size,
            desc=f"{year} | {file.name}",
            unit="B",
            unit_scale=True,
            leave=False,
            disable=not show_file_progress,
        )
        bytes_since_update = 0

        try:
            with file.open("rb", buffering=1024 * 1024) as fh:
                for line in fh:
                    n_raw += 1
                    bytes_since_update += len(line)

                    income = _parse_int_field(line, income_start, income_end)

                    if income is None:
                        n_invalid_income += 1
                    elif (
                        income == missing_income
                        or income in GLOBAL_INCOME_SENTINELS
                    ):
                        n_missing_income += 1
                    elif has_member:
                        member = _parse_int_field(line, member_start, member_end)

                        if member is None or member <= 0:
                            n_invalid_member += 1
                        else:
                            incomes.append(income / member)
                    else:
                        incomes.append(float(income))

                    if bytes_since_update >= 4 * 1024 * 1024:
                        progress.update(bytes_since_update)
                        bytes_since_update = 0

            if bytes_since_update:
                progress.update(bytes_since_update)
        finally:
            progress.close()

    df_refined = pd.DataFrame(
        {
            "renda": pd.Series(incomes, dtype="float64"),
            "ano": year,
        }
    )

    stats = {
        "ano": year,
        "arquivos": len(files),
        "n_raw": n_raw,
        "n_refined": len(df_refined),
        "n_missing_renda": n_missing_income,
        "n_invalid_renda": n_invalid_income,
        "n_invalid_morador": n_invalid_member if has_member else 0,
        "per_capita": has_member,
    }

    return df_refined, stats


def generate_datasets(
    metadata_path=DEFAULT_METADATA_PATH,
    raw_path=DEFAULT_RAW_PATH,
    refined_path=DEFAULT_REFINED_PATH,
    show_file_progress=True,
    show_year_progress=True,
):
    """Generate all annual refined datasets and return the processing summary."""
    raw_path = Path(raw_path)
    refined_path = Path(refined_path)

    if not raw_path.is_dir():
        raise FileNotFoundError(f"Raw-data directory not found: {raw_path}")

    refined_path.mkdir(parents=True, exist_ok=True)

    df_metadata = load_metadata(metadata_path)
    available = get_available_specs(df_metadata)
    summary = []

    years_progress = tqdm(
        available.itertuples(index=False),
        total=len(available),
        desc="PNAD",
        unit="year",
        disable=not show_year_progress,
    )

    for spec in years_progress:
        year = int(spec.ano)
        years_progress.set_postfix_str(str(year))
        t0 = perf_counter()

        df_refined, stats = read_year_fast(
            spec,
            raw_path=raw_path,
            show_file_progress=show_file_progress,
        )

        if df_refined.empty:
            raise RuntimeError(f"Empty refined dataset for {year}.")
        if df_refined["renda"].isna().any():
            raise RuntimeError(f"NaN income values after processing {year}.")
        if df_refined["renda"].isin(GLOBAL_INCOME_SENTINELS).any():
            raise RuntimeError(f"Global income sentinel survived processing {year}.")
        if not (df_refined["ano"] == year).all():
            raise RuntimeError(f"Inconsistent year column for {year}.")

        output_file = refined_path / f"pnad_refined_{year}.parquet"
        df_refined.to_parquet(
            output_file,
            index=False,
            compression="snappy",
        )

        stats["tempo_s"] = perf_counter() - t0
        stats["output"] = output_file.name
        summary.append(stats)
        del df_refined

    df_summary = pd.DataFrame(summary)

    if len(df_summary) != len(available):
        raise RuntimeError("Processing summary is inconsistent with available years.")
    if not df_summary["ano"].is_unique:
        raise RuntimeError("Processing summary contains duplicated years.")

    return df_summary


def main():
    """Run the complete raw-to-refined dataset generation."""
    return generate_datasets()


if __name__ == "__main__":
    df_summary = main()
    print(df_summary.to_string(index=False))
